name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: usersdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 10
    env:
      DB_HOST: localhost
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: usersdb
      DB_PORT: 5432
      APP_PORT: 8080
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client
      - name: Wait for Postgres
        run: |
          for i in {1..20}; do
            pg_isready -h localhost -U postgres && break
            sleep 2
          done
          psql -h localhost -U postgres -d usersdb -c 'SELECT 1;' || (echo "Postgres not ready" && exit 1)
        env:
          PGPASSWORD: postgres
      - name: Install dependencies
        run: go mod download
      - name: Run tests
        run: go test -v
